// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSeESdXSxPnZmZpTeluKekaPBg9GVnO84',
    appId: '1:280566471374:web:994b601792531901680e9f',
    messagingSenderId: '280566471374',
    projectId: 'snakegame-0123',
    authDomain: 'snakegame-0123.firebaseapp.com',
    storageBucket: 'snakegame-0123.appspot.com',
    measurementId: 'G-95S59Q1TSD',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWbx0YOnR2tt2Jj-FqA4IPYFqpWFlP3dU',
    appId: '1:280566471374:android:914b5f5462c6290f680e9f',
    messagingSenderId: '280566471374',
    projectId: 'snakegame-0123',
    storageBucket: 'snakegame-0123.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtrpPHeSiWegb1AaitpEHWQzVbBTl_T_Q',
    appId: '1:280566471374:ios:5d0b846b4acf1c98680e9f',
    messagingSenderId: '280566471374',
    projectId: 'snakegame-0123',
    storageBucket: 'snakegame-0123.appspot.com',
    iosClientId: '280566471374-cmfhu1f0m7lfvgv3li9k39jisla5s647.apps.googleusercontent.com',
    iosBundleId: 'com.example.gdscApp',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtrpPHeSiWegb1AaitpEHWQzVbBTl_T_Q',
    appId: '1:280566471374:ios:5d0b846b4acf1c98680e9f',
    messagingSenderId: '280566471374',
    projectId: 'snakegame-0123',
    storageBucket: 'snakegame-0123.appspot.com',
    iosClientId: '280566471374-cmfhu1f0m7lfvgv3li9k39jisla5s647.apps.googleusercontent.com',
    iosBundleId: 'com.example.gdscApp',
  );
}
